'use strict';

module.exports = {
    base: require('*/cartridge/models/product/decorators/base'),
    types: require('*/cartridge/models/product/decorators/types'),
    availability: require('*/cartridge/models/product/decorators/availability'),
    description: require('*/cartridge/models/product/decorators/description'),
    images: require('*/cartridge/models/product/decorators/images'),
    price: require('*/cartridge/models/product/decorators/price'),
    searchPrice: require('*/cartridge/models/product/decorators/searchPrice'),
    promotions: require('*/cartridge/models/product/decorators/promotions'),
    quantity: require('*/cartridge/models/product/decorators/quantity'),
    quantitySelector: require('*/cartridge/models/product/decorators/quantitySelector'),
    ratings: require('*/cartridge/models/product/decorators/ratings'),
    sizeChart: require('*/cartridge/models/product/decorators/sizeChart'),
    variationAttributes: require('*/cartridge/models/product/decorators/variationAttributes'),
    searchVariationAttributes: require('*/cartridge/models/product/decorators/searchVariationAttributes'),
    attributes: require('*/cartridge/models/product/decorators/attributes'),
    options: require('*/cartridge/models/product/decorators/options'),
    currentUrl: require('*/cartridge/models/product/decorators/currentUrl'),
    readyToOrder: require('*/cartridge/models/product/decorators/readyToOrder'),
    setReadyToOrder: require('*/cartridge/models/product/decorators/setReadyToOrder'),
    bundleReadyToOrder: require('*/cartridge/models/product/decorators/bundleReadyToOrder'),
    setIndividualProducts: require('*/cartridge/models/product/decorators/setIndividualProducts'),
    bundledProducts: require('*/cartridge/models/product/decorators/bundledProducts'),
    bonusUnitPrice: require('*/cartridge/models/product/decorators/bonusUnitPrice'),
    raw: require('*/cartridge/models/product/decorators/raw'),
    replacesParts: require('*/cartridge/models/product/decorators/replacesParts'),
    pageMetaData: require('*/cartridge/models/product/decorators/pageMetaData'),
    pdpMainVideo: require('*/cartridge/models/product/decorators/pdpMainVideo'),
    specification: require('*/cartridge/models/product/decorators/specification'),
    setIndividualProductIds: require('*/cartridge/models/product/decorators/setIndividualProductIds'),
    setExtendedWarranty: require('*/cartridge/models/product/decorators/setExtendedWarranty'),
    licensedProducts: require('*/cartridge/models/product/decorators/licensedProducts'),
    videos: require('*/cartridge/models/product/decorators/videos')
};
